# Generated by Django 6.0.4 on 2026-04-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_usuario_is_cliente_remove_usuario_is_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rif',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
