# Generated by Django 6.0.4 on 2026-05-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_usuario_apellido_remove_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
