# Generated by Django 6.0.5 on 2026-05-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_usuario_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('especializado', 'Especializado'), ('urgencias', 'Urgencias'), ('estetico', 'Estético')], default='general', max_length=50),
        ),
    ]
