# Generated by Django 6.0.5 on 2026-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
