# Generated by Django 6.0.5 on 2026-05-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_servicio_activo_alter_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
