# Generated by Django 6.0.5 on 2026-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_add_cancelada_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('salud', 'Salud y Medicina'), ('bienestar', 'Barbería y Estética'), ('deporte', 'Deporte y Fitness'), ('educacion', 'Educación y Tutorías'), ('asesoria', 'Asesoría y Consultoría'), ('hogar', 'Hogar y Reparaciones'), ('tecnologia', 'Tecnología y Soporte'), ('creatividad', 'Diseño y Creatividad'), ('automotriz', 'Automotriz'), ('general', 'General / Otros')], default='general', max_length=50),
        ),
    ]
