# Generated by Django 6.0.5 on 2026-06-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
